#pragma once
#include <stdlib.h>
#include <iostream>
#include <cmath>
#include "Action.h"
#include "Object.h"
#include "Controller.h"
#include "ExtendedRenderWindow.h"
#include "Scene.h"
#include "SceneLayer.h"
#include "Camera.h"
#include "CollisionDetection.h"
#include "CollisionGraph.h"
#include "Gravity.h"
#include "AirFriction.h"
#include "PhysicsManager.h"
#include "PropertyNode.h"
#include "HitboxNode.h"
#include <SFML/Graphics.hpp>
#include <SFML/System/Time.hpp>
